# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designv5.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 480)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(800, 480))
        MainWindow.setMaximumSize(QtCore.QSize(800, 480))
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.BlankCursor))
        self.txtWOID = QtWidgets.QLineEdit(MainWindow)
        self.txtWOID.setGeometry(QtCore.QRect(320, 130, 151, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.txtWOID.setFont(font)
        self.txtWOID.setAlignment(QtCore.Qt.AlignCenter)
        self.txtWOID.setObjectName("txtWOID")
        self.txtPart = QtWidgets.QLineEdit(MainWindow)
        self.txtPart.setGeometry(QtCore.QRect(320, 220, 151, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.txtPart.setFont(font)
        self.txtPart.setAlignment(QtCore.Qt.AlignCenter)
        self.txtPart.setObjectName("txtPart")
        self.btnEnter = QtWidgets.QPushButton(MainWindow)
        self.btnEnter.setGeometry(QtCore.QRect(230, 320, 251, 111))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.btnEnter.setFont(font)
        self.btnEnter.setObjectName("btnEnter")
        self.lblWOID = QtWidgets.QLabel(MainWindow)
        self.lblWOID.setGeometry(QtCore.QRect(40, 140, 241, 41))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.lblWOID.setFont(font)
        self.lblWOID.setAlignment(QtCore.Qt.AlignCenter)
        self.lblWOID.setObjectName("lblWOID")
        self.lblPart = QtWidgets.QLabel(MainWindow)
        self.lblPart.setGeometry(QtCore.QRect(40, 230, 241, 41))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.lblPart.setFont(font)
        self.lblPart.setAlignment(QtCore.Qt.AlignCenter)
        self.lblPart.setObjectName("lblPart")
        self.btnClear = QtWidgets.QPushButton(MainWindow)
        self.btnClear.setGeometry(QtCore.QRect(80, 320, 121, 111))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.btnClear.setFont(font)
        self.btnClear.setObjectName("btnClear")
        self.lblQty = QtWidgets.QLabel(MainWindow)
        self.lblQty.setGeometry(QtCore.QRect(570, 30, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.lblQty.setFont(font)
        self.lblQty.setText("")
        self.lblQty.setAlignment(QtCore.Qt.AlignCenter)
        self.lblQty.setObjectName("lblQty")
        self.lblPartReturn = QtWidgets.QLabel(MainWindow)
        self.lblPartReturn.setGeometry(QtCore.QRect(50, 270, 511, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.lblPartReturn.setFont(font)
        self.lblPartReturn.setText("")
        self.lblPartReturn.setAlignment(QtCore.Qt.AlignCenter)
        self.lblPartReturn.setObjectName("lblPartReturn")
        self.lblWOIDReturn = QtWidgets.QLabel(MainWindow)
        self.lblWOIDReturn.setGeometry(QtCore.QRect(50, 180, 511, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.lblWOIDReturn.setFont(font)
        self.lblWOIDReturn.setText("")
        self.lblWOIDReturn.setAlignment(QtCore.Qt.AlignCenter)
        self.lblWOIDReturn.setObjectName("lblWOIDReturn")
        self.slQty = QtWidgets.QSlider(MainWindow)
        self.slQty.setGeometry(QtCore.QRect(690, 30, 22, 411))
        self.slQty.setMinimum(1)
        self.slQty.setMaximum(10)
        self.slQty.setPageStep(1)
        self.slQty.setOrientation(QtCore.Qt.Vertical)
        self.slQty.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.slQty.setTickInterval(1)
        self.slQty.setObjectName("slQty")
        self.txtClockID = QtWidgets.QLineEdit(MainWindow)
        self.txtClockID.setGeometry(QtCore.QRect(320, 70, 151, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.txtClockID.setFont(font)
        self.txtClockID.setAlignment(QtCore.Qt.AlignCenter)
        self.txtClockID.setObjectName("txtClockID")
        self.lblClockID = QtWidgets.QLabel(MainWindow)
        self.lblClockID.setGeometry(QtCore.QRect(40, 80, 241, 41))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.lblClockID.setFont(font)
        self.lblClockID.setAlignment(QtCore.Qt.AlignCenter)
        self.lblClockID.setObjectName("lblClockID")
        self.lcdTime = QtWidgets.QLCDNumber(MainWindow)
        self.lcdTime.setGeometry(QtCore.QRect(323, 12, 141, 41))
        self.lcdTime.setObjectName("lcdTime")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Freeman Part Issuing"))
        self.btnEnter.setText(_translate("MainWindow", "Enter"))
        self.lblWOID.setText(_translate("MainWindow", "Work Order"))
        self.lblPart.setText(_translate("MainWindow", "Part Number"))
        self.btnClear.setText(_translate("MainWindow", "Clear"))
        self.lblClockID.setText(_translate("MainWindow", "Clock #"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QDialog()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

