# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'partsdialog.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 800)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1280, 800))
        MainWindow.setMaximumSize(QtCore.QSize(1280, 800))
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.BlankCursor))
        self.txtWOBOMID = QtWidgets.QLineEdit(MainWindow)
        self.txtWOBOMID.setGeometry(QtCore.QRect(400, 260, 161, 61))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.txtWOBOMID.setFont(font)
        self.txtWOBOMID.setAlignment(QtCore.Qt.AlignCenter)
        self.txtWOBOMID.setObjectName("txtWOBOMID")
        self.btnEnter = QtWidgets.QPushButton(MainWindow)
        self.btnEnter.setGeometry(QtCore.QRect(580, 640, 611, 141))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.btnEnter.setFont(font)
        self.btnEnter.setObjectName("btnEnter")
        self.lblWOBOMID = QtWidgets.QLabel(MainWindow)
        self.lblWOBOMID.setGeometry(QtCore.QRect(10, 270, 381, 41))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.lblWOBOMID.setFont(font)
        self.lblWOBOMID.setAlignment(QtCore.Qt.AlignCenter)
        self.lblWOBOMID.setObjectName("lblWOBOMID")
        self.btnClear = QtWidgets.QPushButton(MainWindow)
        self.btnClear.setGeometry(QtCore.QRect(80, 640, 251, 141))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.btnClear.setFont(font)
        self.btnClear.setObjectName("btnClear")
        self.lblQty = QtWidgets.QLabel(MainWindow)
        self.lblQty.setGeometry(QtCore.QRect(650, 250, 141, 81))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.lblQty.setFont(font)
        self.lblQty.setText("")
        self.lblQty.setAlignment(QtCore.Qt.AlignCenter)
        self.lblQty.setObjectName("lblQty")
        self.lblPartReturn = QtWidgets.QLabel(MainWindow)
        self.lblPartReturn.setGeometry(QtCore.QRect(50, 440, 571, 51))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.lblPartReturn.setFont(font)
        self.lblPartReturn.setText("")
        self.lblPartReturn.setAlignment(QtCore.Qt.AlignCenter)
        self.lblPartReturn.setObjectName("lblPartReturn")
        self.lblWOIDReturn = QtWidgets.QLabel(MainWindow)
        self.lblWOIDReturn.setGeometry(QtCore.QRect(50, 370, 571, 51))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.lblWOIDReturn.setFont(font)
        self.lblWOIDReturn.setText("")
        self.lblWOIDReturn.setAlignment(QtCore.Qt.AlignCenter)
        self.lblWOIDReturn.setObjectName("lblWOIDReturn")
        self.txtClockID = QtWidgets.QLineEdit(MainWindow)
        self.txtClockID.setGeometry(QtCore.QRect(400, 120, 161, 61))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.txtClockID.setFont(font)
        self.txtClockID.setAlignment(QtCore.Qt.AlignCenter)
        self.txtClockID.setObjectName("txtClockID")
        self.lblClockID = QtWidgets.QLabel(MainWindow)
        self.lblClockID.setGeometry(QtCore.QRect(30, 130, 361, 41))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.lblClockID.setFont(font)
        self.lblClockID.setAlignment(QtCore.Qt.AlignCenter)
        self.lblClockID.setObjectName("lblClockID")
        self.lcdTime = QtWidgets.QLCDNumber(MainWindow)
        self.lcdTime.setGeometry(QtCore.QRect(510, 10, 261, 81))
        self.lcdTime.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lcdTime.setObjectName("lcdTime")
        self.btn1 = QtWidgets.QPushButton(MainWindow)
        self.btn1.setGeometry(QtCore.QRect(820, 90, 113, 111))
        font = QtGui.QFont()
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.btn1.setFont(font)
        self.btn1.setObjectName("btn1")
        self.btn2 = QtWidgets.QPushButton(MainWindow)
        self.btn2.setGeometry(QtCore.QRect(950, 90, 113, 111))
        font = QtGui.QFont()
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.btn2.setFont(font)
        self.btn2.setObjectName("btn2")
        self.btn3 = QtWidgets.QPushButton(MainWindow)
        self.btn3.setGeometry(QtCore.QRect(1080, 90, 113, 111))
        font = QtGui.QFont()
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.btn3.setFont(font)
        self.btn3.setObjectName("btn3")
        self.btn4 = QtWidgets.QPushButton(MainWindow)
        self.btn4.setGeometry(QtCore.QRect(820, 210, 113, 111))
        font = QtGui.QFont()
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.btn4.setFont(font)
        self.btn4.setObjectName("btn4")
        self.btn5 = QtWidgets.QPushButton(MainWindow)
        self.btn5.setGeometry(QtCore.QRect(950, 210, 113, 111))
        font = QtGui.QFont()
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.btn5.setFont(font)
        self.btn5.setObjectName("btn5")
        self.btn6 = QtWidgets.QPushButton(MainWindow)
        self.btn6.setGeometry(QtCore.QRect(1080, 210, 113, 111))
        font = QtGui.QFont()
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.btn6.setFont(font)
        self.btn6.setObjectName("btn6")
        self.btn7 = QtWidgets.QPushButton(MainWindow)
        self.btn7.setGeometry(QtCore.QRect(820, 330, 113, 111))
        font = QtGui.QFont()
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.btn7.setFont(font)
        self.btn7.setObjectName("btn7")
        self.btn8 = QtWidgets.QPushButton(MainWindow)
        self.btn8.setGeometry(QtCore.QRect(950, 330, 113, 111))
        font = QtGui.QFont()
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.btn8.setFont(font)
        self.btn8.setObjectName("btn8")
        self.btn9 = QtWidgets.QPushButton(MainWindow)
        self.btn9.setGeometry(QtCore.QRect(1080, 330, 113, 111))
        font = QtGui.QFont()
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.btn9.setFont(font)
        self.btn9.setObjectName("btn9")
        self.btn0 = QtWidgets.QPushButton(MainWindow)
        self.btn0.setGeometry(QtCore.QRect(820, 450, 113, 111))
        font = QtGui.QFont()
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.btn0.setFont(font)
        self.btn0.setObjectName("btn0")
        self.btnClearQty = QtWidgets.QPushButton(MainWindow)
        self.btnClearQty.setGeometry(QtCore.QRect(950, 450, 241, 111))
        font = QtGui.QFont()
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.btnClearQty.setFont(font)
        self.btnClearQty.setObjectName("btnClearQty")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Freeman Part Issuing"))
        self.btnEnter.setText(_translate("MainWindow", "Enter"))
        self.lblWOBOMID.setText(_translate("MainWindow", "Work Order BOM #"))
        self.btnClear.setText(_translate("MainWindow", "Clear"))
        self.lblClockID.setText(_translate("MainWindow", "Clock #"))
        self.btn1.setText(_translate("MainWindow", "1"))
        self.btn2.setText(_translate("MainWindow", "2"))
        self.btn3.setText(_translate("MainWindow", "3"))
        self.btn4.setText(_translate("MainWindow", "4"))
        self.btn5.setText(_translate("MainWindow", "5"))
        self.btn6.setText(_translate("MainWindow", "6"))
        self.btn7.setText(_translate("MainWindow", "7"))
        self.btn8.setText(_translate("MainWindow", "8"))
        self.btn9.setText(_translate("MainWindow", "9"))
        self.btn0.setText(_translate("MainWindow", "0"))
        self.btnClearQty.setText(_translate("MainWindow", "Clear"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QDialog()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

